- readme.md
- readme.txt
The current description didn't make it really clear to me that this was an option without coding stuff into the WordPress core or maybe to the WPCron (does that still exist btw? haven't worked with WP for years).
> How to enable WebMentions without coding

- webmention.php
If there was an & in the target, it would not be found by a simple
string search of the HTML source.  Do special character unescaping to
solve this.
> Accept targets containing &

- class-webmention-sender.php
This replaces make_absolute_url with the built in version of same, and replaces a pure instance of parse_url, with wp_parse_url...a wrapper which supports schemeless URLs on earlier versions of PHP
> Replace with built-in WordPress functions

- includes/class-webmention-receiver.php
- includes/class-webmention-sender.php
- webmention.php
Relocate files to includes directory. Remove duplicate functions. Add check for the same domain. And remove extra retrieval of URL by switching from get_meta_tags(which retrieves the HTML again) to a custom function based on the code in the Press This functionality.
> Relocate Files to Includes and Remove Duplication

- includes/class-webmention-receiver.php
- webmention.php
This swaps the target verification before the source. To assist in that, it starts creating the $commentdata array and passes that, as it will be needed anyway.
The default request handler is now responsible for source verification and content creation...which means it could be replaced with an async handler as needed.
'vouch' is now a parameter passed into the comment array, which allows for vouch testing support at the preprocess_comment level or a handler that will handle vouch to be used. 
To match changes made to pingbacks in WordPress, it now passes variables remote_source and remote_source original into the commentdata. This will allow a future update to Semantic Linkbacks that will avoid it having to pull the source an additional time. 
Also fixed an error in the latest …
> Target Before Source Verification and Related Changes

- includes/class-webmention-sender.php
- readme.md
- readme.txt
fixes #98. the Ultimate Category Excluder plugin (https://wordpress.org/plugins/ultimate-category-excluder/) filters get_posts to hide user-defined categories, but we're not displaying posts here, so temporarily disable it.
this is a noop for users who don't have Ultimate Category Excluder installed.
cc @pfefferle, @dshanske
> fix incompatibility with Ultimate Category Excluder plugin

- includes/class-webmention-receiver.php
- webmention.php
This changes to the new flood filter and supports register_settings for default. 
It also instructs a WP_Error return instead of wp_die as a return of a WP_Error indicates that we aren't handling things correctly. But this can't be addressed if the code dies.
I'd like it if there was a way to handle flooding, being as webmentions should be protected against it, but that doesn't work with the filter we have.
> Take Advantage of 4.7

- .travis.yml
- includes/class-webmention-sender.php
- readme.md
- readme.txt
- templates/webmention-discussion-settings.php
- webmention.php
This PR adds a post type support feature called 'webmentions' which is automatically added to type 'post', added if a setting is set to 'page', and would require any custom post types to add or note during declaration.
This setting will open or close ping status by default. The sending of webmentions is now limited to post types that support this setting.
This allows a much clearer way to declare support for webmentions with custom post types and can be used to send/receive them. It also removes the issue created when WordPress disabled ping status support by default for pages and post types that didn't declare trackbacks support.
Because the logic of how support is maintained is now handled by the Webmentions plugin, if we decide to, in future, not rely on ping_status to determine …
> Webmention Supports

- includes/class-webmention-receiver.php
- readme.md
- readme.txt
- webmention.php
This is to support storing webmention source and creation time in meta. 
The reasoning is that creation time is overwritten by Semantic Linkbacks and allows for the original time to be compared to the modified time, which is not stored in the comment table.
The source is stored, like pingbacks, in the author_url, which results in duplication of purpose, especially in Semantic Linkbacks. The code will still look at the comment_author_url if there is no matching meta property. 
Realized during this that the fragment and target code previously written executes after Semantic Linkbacks, so had to move everything earlier in the chain of events. 
The goal is to have webmentions move a bit away from the pingback mirrored implementation, but still keeping backward compatibility with that. That …
> Support Creation Time and Webmention Source Storage

- includes/class-webmention-receiver.php
- includes/class-webmention-vouch.php
- languages/webmention.pot
- readme.md
- readme.txt
- templates/webmention-api-message.php
- webmention.php
This PR adds in the ability to add domains to the whitelist from the comment admin,  as well as preliminary support for receiving vouches.
For now, the code, if there is a vouch parameter, verifies it. If it fails verification, it rejects the webmention. If it passes, it adds a parameter noting it passed. It also stores the vouch. It uses the approved domains list to determine acceptable sites for vouching, but I'd like to expand verification in future.
The next piece would be to add an admin setting to decide whether or not a successful vouch should be auto-approved, and to start getting some vouched webmentions.
> Receiving Vouches

- .travis.yml
- Gruntfile.js
- includes/class-webmention-admin.php
- includes/class-webmention-sender.php
- includes/functions.php
- languages/webmention.pot
- phpcs.xml
- readme.md
- readme.txt
- templates/webmention-comment.php
- templates/webmention-settings.php
- webmention.php
This started as simply adding attachment support, but in order to support that, I upgraded the setting to allow one to add webmention support to any public post type.
webmention_to_post_id now tries to match attachment files to the attachment post id. 
In exploring this, and realizing that I couldn't support receiving webmentions to media files without adding the header on the server level(Thanks @pfefferle for leading me to that conclusion when it eluded me), I looked at the fact that we were sending out webmentions for every link in a post, and links in img, video, or audio tags would almost never be relevant, and there were other HTML elements that it made no sense to send webmentions for.
So now, it actually extracts valid links, not just URLs in content.
> Attachments

- includes/class-webmention-receiver.php
- includes/functions.php
- webmention.php
Address #75 and #152 
The problem with hiding headers prior was partially that is_singular() or anything requiring a global query variable isn't loaded when headers are sent, so it would always evaluate to false.
This uses get_self_link(scheduled for WordPress 5.3, see https://core.trac.wordpress.org/ticket/44838) to retrieve the URL currently being requested, then determines the post_id if applicable using webmention_to_postid, which means the existing filter could take archive or other pages and redirect them. It also works for the currently built in home page mention redirect.
> Hide headers if webmentions are not supported to that URL

- includes/class-webmention-avatar-handler.php
Fixes #248 
This moves the checking for whether an email exists from the anoynmous code into the check_gravatar function. It also passes the arguments array, optionally in and checks to see if the URL passed in it is a gravatar URL. If so, it extracts the hash and runs the same check.
This should fix the problem.
> Cache in cases where stored avatar is a gravatar

- includes/class-webmention-avatar-handler.php
Still working on fixes for the avatar situation. Noticed another mistake here...since comment_type for comments is '', this wasn't recognizing comments as a comment type. Switched to get_comment_type that should be used.
> Fix issue where comment type was not recognized

- includes/class-webmention-admin.php
- includes/class-webmention-receiver.php
- languages/webmention.pot
- readme.md
- readme.txt
- webmention.php
This addresses #252 and is an alternative to #254. Props to @jeremyfelt who identified that the issue is the wp_allow_comment function interfering even though the comment_approved is set.
Now, the WEBMENTION_COMMENT_APPROVE flag has been there for years, even before the domain approval list. So, something else we changed created this situation. Either way, moving both checks to wp_allow_comment seems more consistent with the flow of adding a comment than setting it earlier.
At the same time, addressed the issue re the term whitelist. I did not change the function name, as it might be called elsewhere, but did change everything else.
Also bumped version to 4.0.3 for easy release.
> Fix Comment Approval Alternate

- includes/functions.php
If the HTML for a front-end view is built from post meta, it is possible that the `post_content` field for a post is empty. If empty content is parsed via `DOMDocument`, a PHP warning is shown:
`DOMDocument::loadHTML(): Empty string supplied as input`
This change skips the extraction of URLs for empty content and returns an empty array instead.
> Don't parse empty content for URLs

- includes/class-webmention-admin.php
- includes/class-webmention-comment-type.php
- includes/functions.php
- webmention.php
The idea here is a simple registration class for the webmention comment types based on the register_post_type function. 
So far, it incorporates the strings used for the various internal labels and menus, but eventually would add others as needed.
Essentially, it is an alternative to adding strings in five different places when adding a new type. And it will make it easier to add additional configuration options as needed.
If WordPress ever adds its own comment type registration, this would replace that.
> Add functionality to register a webmention comment type

- includes/class-webmention-sender.php
Had a look at core.
https://github.com/WordPress/WordPress/blob/3dda74c3377243797ceffb429f94e0ea63ad6d75/wp-includes/default-filters.php#L358
The _publish_post_hook is at priority 5.
https://github.com/WordPress/WordPress/blob/3da046e1bce8408a1b6cd08e03eaf69a6bb506cd/wp-includes/post.php#L7029
The function is what triggers do_pings. So _mentionme should be added before this is scheduled. And it is scheduled to occur immediately at priority 5. So the webmention trigger should be ahead of that at 3 or 4.
> Change priority of publish hook

- includes/class-webmention-request.php
https://wordpress.org/support/topic/error-cannot-find-target-link/
The error isn't related to specifically to what was reported, but it reveals a mistake in not passing the response variable optionally to be used.
> Fix issue with response not being passed to response code.

- includes/Handler/class-wp.php
This splits up the new WP handler to individual pieces that could be tested.
> REST API Parse Improvements

- templates/webmention-comment-form.php
Would you be open to adding hooks in the different templates available in the plugin?  This would allow one to add content before or after the webmention form, without having to overwrite the full template.
For example, one could add an HTML element between the comment form and the webmention form, without having to rely on custom CSS or having to define their own custom `templates/webmention-comment-form.php` via the existing `webmention_comment_form` filter.
```php
add_action(
'webmention_comment_form_template_before',
function () {
echo '<hr class="styled-separator is-style-wide" aria-hidden="true">';
}
);
```
What do you think?
> Comment form template: add hooks before and after the form

- includes/class-comment-type.php
- includes/class-comment.php
- readme.md
- readme.txt
- webmention.php
Started doing some user testing on a live test site and noticed this bug with the comment types. We never set the singular property and that is used in the Comment Admin screen.
> Fixes an Issue in Comment Types

- includes/class-receiver.php
This would result in a couple PHP warnings and cause the `webmention_vouch_url` to always store as an empty string, even if a vouch URL was provided.
```bash
wp> $vouch = urldecode( $params['vouch'] );
=> string(0) ""
wp> esc_url_raw( $vouch );
=> string(0) ""
```
> Use available `$vouch` instead of `$params['vouch']`

- includes/class-admin.php
This is the simplest way of ensuring migration is checked after activation. It runs the upgrade check each time you visit the settings page, so that avoids checking it on every page load, in the event it doesn't trigger on upgrade.
I thought about more complicated options, but this covers us in most cases.
> Check version when settings page is loaded

- includes/class-sender.php
Addresses #346. There is no concern about extra performance load because it only triggers on the case of a webmention enabled post type, and it checks to see if do_pings is already scheduled.
> Add support for CPTs

- includes/class-receiver.php
This updates the dupe check parameters to search for dupes by matching on webmention_source_url, url, _crossposting_link or source_url in one query instead of multiple queries. 
webmention_source url = the original source url
url = the canonical url in the event of something like a Bridgy post
_crossposting_link for Salmon
source_url for ActivityPub
> Update dupe check

- includes/class-db.php
- tests/test-db.php
This bumps the schema to 1.0.1 in order to run a function to extract the author url from mf2_author and update author_url.
> Add mf2 author migration

- includes/class-receiver.php
Resolves #341
The code shows 'any' as an option, but the documentation doesn't. Filed a ticket. If I read WP_Comment_query correctly, all actually doesn't include spam and trash, but any does.
> Include spam and trash statuses for dupe check

- includes/Handler/class-meta.php
This is based on the webmention sent from https://minutestomidnight.co.uk/notes/2023-07-13-10-52-06/ to 
https://tracydurnell.com/2023/07/12/barriers-to-a-more-social-indieweb/ where the content is actually wrong and coming from meta when a better microformats options is there.
> Switch from set to add to avoid meta overriding mf2

- includes/Entity/class-item.php
If the response type is expressly set to comment, then this will always return the full content. Otherwise, it will return the content if it is short enough, if not the summary, if not the name, if not nothing.
I debated on the nothing vs a generated excerpt. But if we were to do a generated excerpt, I'd want to discuss how we'd excerpt as a topic. For example, number of characters = MAX_INLINE_MENTION_LENGTH? Try to mirror Pingbacks and get the context around the link to the target? Etc.
> Use summary when appropriate

- readme.md
- readme.txt
- webmention.php
Instead of enqueuing the Webmention CSS on all pages of the site, we could try only enqueuing it on singular pages (posts / pages / CPTs) where comments are open.
> Performance: only enqueue CSS on pages with a comment form

- includes/Handler/class-wp.php
- includes/class-response.php
This adds functions to retrieve HTML links in the response class and then uses it in the wp search if it can't find an API link in the header.
> Introduce HTML link search and add it to wp as a fallback

- includes/Handler/class-wp.php
- includes/class-discovery.php
- includes/class-response.php
- tests/test-discovery.php
- tests/test-handler-wp.php
Simplify the discovery mechanism by introducing a `get_links_by` function in the Response Object, that checks HTML and HTTP-Header Links.
> simplify html/head link discovery

- includes/class-comment.php
- includes/functions.php
See: https://wordpress.org/support/topic/breaks-ordinary-comment-permalink-links/
> use source-link only on frontend and for Webmentions

- includes/class-avatar-store.php
- webmention.php
This brings back the Local Avatar Store code we wrote two years ago, in a minimalist manner, and it adds it to the repo disabled by default.
The way it is set up, as you may recall(as you co-wrote it), since it updates the Avatar property, if you disable it, it will retain for the existing updated ones, but it won't revert to remote loading until the next time the webmention is updated.
> Add Optional Avatar Store

- includes/class-receiver.php
- languages/webmention.pot
- readme.md
- readme.txt
- webmention.php
In the current code, we bypass spam detection completely, because every Webmentions is always only `1` or `0`.
That makes spam detection useless and with spammers keeping up with new technologies like Webmentions, we should not bother our users to check every Mention.
What do you think @dshanske 
/cc @kbrown9 and @cybeardjm
> Do not bypass spam detection

- includes/Handler/class-mf2.php
- includes/class-comment.php
- includes/class-receiver.php
- includes/functions.php
- tests/data/mf2/brid-gy.html
- tests/data/mf2/sandeep-io.html
This addresses #444 and creates the 'update' comment type, indicating a source update notification. For now, it doesn't store it in the database, but it adds a hook for someone to add notifications or otherwise on it.
It also, as a precaution, adds a check for unregistered webmention comment types being added. This is to ensure if someone adds something custom to the map, they register it.
> Support Source Update Notifications

- includes/class-comment.php
- languages/webmention.pot
- readme.md
- readme.txt
- webmention.php
When I had it check for comment types, I forgot the built-in ones.
> Add in default comment types

- includes/Entity/class-item.php
Currently the `get_response_type` logic is using the `get_content` function. This function adds some fallbacks for mentions or for the case when the content is empty.
For `mentions` the `get_content` function always returns the summary that is smaller than `MAX_INLINE_MENTION_LENGTH`, so mentions will always be handled as comments.
> fix comment type detection

- includes/class-admin.php
This fails on other comment types like for example ActivityPub: https://github.com/Automattic/wordpress-activitypub/issues/865
> Allow "Approve & Always Allow" only for Webmentions

- includes/class-comment-walker.php
ClassicPress defaults to HTML5, so removed the regular comment function and the format argument. I've opened a bug that they should have kept backcompat on this...having the comment function call the html5 function. This just defaults to HTML5 if no format is set...being as html5 is supposed to default if nothing is set per the WP docs, this should be fine.
> Check for missing format property

- .github/workflows/wp-phpunit.yml
- includes/class-admin.php
- templates/webmention-settings.php
- webmention.php
Adds a setting. Turns on the store by default.
> Add setting for avatar store

- includes/functions.php
- templates/webmention-comment-form.php
Fixes https://github.com/pfefferle/wordpress-webmention/issues/520 and https://github.com/pfefferle/wordpress-webmention/issues/505
> Comment form template improvements
