pfefferle/wordpress-webmention

readme.md
Sorry, not very familiar with this markdown syntax :-)
=> Text edit ended up on the same line

webmention.php
wp_kses is a function to sanitize HTML. I've added wp_kses_post to the remotely pulled contents to prevent things like XSS, hidden iframes, etc.
=> adding kses

webmention.php
If we're updating an existing mention, keep the existing approval
status.
=> Do not unapprove already-approved webmention

includes/class-webmention-sender.php
To add the ability to log errors and successes if desired.
=> Move Hook so Triggers on All Attempts to Send Webmentions

readme.md, readme.txt
Figured I'd get a start on updating the documents part of this.
=> Update README for next release.

includes/class-webmention-receiver.php
get_site_url() includes the wordpress directory, so we want home_url() instead. also don't keep going if we hit this. :P
=> bug fix for check that target is on site

includes/class-webmention-receiver.php, includes/class-webmention-sender.php, includes/deprecations.php, readme.md, readme.txt, webmention.php
Made some tweaks based on the refactoring. Brought back the async option as just a cron hook triggered by a flag.
=> Misc Document and Minor Tweaks to PR/100 Branch

includes/class-webmention-receiver.php, includes/deprecations.php, includes/functions.php
Brought over some of the code I wrote for the REST API infrastructure and adapted it for the plugin here.
Also had to change the priority on the deprecated filters function as it seemed to be blanking the added input.
=> Update to use WordPress API Infrastructure

includes/class-webmention-receiver.php
- Save Fragments of URLs
- Add Avatar Support to Webmentions
- Fix issue with dupes due incorrect query argument
=> Minor Fixes

includes/class-webmention-receiver.php, includes/functions.php, languages/webmention.pot, readme.md, readme.txt, templates/webmention-comment-form.php, templates/webmention-endpoint-form.php, webmention.php
Adds a webmention meta box to the comment edit screen so these fields can be viewed, adds a filter to the webmention_comment_form, adds an edit_webmention hook due to the fact the edit_comment filter doesn't allow for meta updates at this time(needed for Semantic Linkbacks).
=> Some Fixes

includes/class-webmention-admin.php, includes/functions.php, templates/webmention-edit-comment-form.php
=> Form Improvements

includes/class-webmention-admin.php, includes/class-webmention-receiver.php, readme.md, readme.txt, templates/webmention-settings.php
Will be a corresponding semantic linkbacks PR as there is duplicative code there.
=> Add avatar setting to turn on or off this feature

includes/class-webmention-admin.php, includes/class-webmention-receiver.php, includes/class-webmention-vouch.php, templates/webmention-api-message.php, templates/webmention-comment-form.php, templates/webmention-comment.php, templates/webmention-edit-comment-form.php, templates/webmention-endpoint-form.php, templates/webmention-settings.php
There are some outliers of strings that have links in the middle of paragraphs, but this should cover majority of the non-escaped translated strings.
=> lets escape as much as we can

languages/webmention.pot, readme.md, readme.txt, webmention.php
This would be just an update for the readme and the version number to move to version 4.0.0
=> Update readme and version

includes/class-webmention-receiver.php
=> Undefined var in is_source_whitelisted()

includes/class-webmention-sender.php, includes/debug.php, includes/functions.php, webmention.php
Part of ongoing efforts for https://github.com/pfefferle/wordpress-webmention/issues/229
=> Dev docs cleanup and revision

includes/class-webmention-request.php, includes/entities/class-webmention-item.php, includes/handlers/class-webmention-handler-meta.php, tests/data/open-graph-test.html, tests/test-discovery.php, tests/test-handler-meta.php
I think we do not need a fully fledged meta-parser, so I think we can simplify the code.
=> simplify parser

includes/class-webmention-notifications.php, includes/class-webmention-receiver.php
rework https://github.com/pfefferle/wordpress-webmention/compare/5.X...errorlogfixes?expand=1
=> fix warnings/errors

includes/Handler/class-mf2.php, includes/class-comment-type.php, includes/class-comment.php, includes/functions.php, tests/data/mf2/aaronparecki-com.json, tests/data/mf2/basic-multi.json, tests/data/mf2/basic-reply-2.json, tests/data/mf2/basic-reply.json, tests/data/mf2/basic-with-comments.json, tests/data/mf2/brid-gy-emoji.json, tests/data/mf2/brid-gy-invite.json, tests/data/mf2/checkmention-hcardxss.json, tests/data/mf2/checkmention-xss.json, tests/data/mf2/notizblog-org.json, tests/data/mf2/voxpelli-com.json, webmention.php
Implements the Webmention Comment/Response UI.
=> Comment Handling

includes/class-webmention-request.php
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/451
=> Incorrect HTTP Status Code

.github/workflows/deploy.yml, .github/workflows/phpcs.yml, .github/workflows/phpunit.yml, .github/workflows/update-assets.yml, composer.json, includes/Handler/class-wp.php
I updated the dependencies on this, and ran the tests, but noticed an issue with the wp rest api call...I found a way to reduce a function call by asking for the authorship data to be embedded. This will change the creation of future tests.
=> Update Dependencies, Actions and WP Requestor

.github/workflows/phpunit.yml, docker-compose-test.yml, includes/class-cli.php, includes/class-db.php, tests/test-db.php, webmention.php
=> DB migration

tests/test-webmention.php, webmention.php
In a lot of different ways... to get really sure ;)
=> Remove Semantic Linkbacks plugin

includes/class-sender.php, includes/class-tools.php
They don't harm anything, but they're unused. 😄
=> Remove unused variables

includes/class-cli.php
fix dummy-data generator to match current db schema
=> [CLI] fix meta-keys

includes/Entity/class-item.php, includes/Handler/class-meta.php, includes/Handler/class-mf2.php, includes/Handler/class-wp.php
Addresses #284 
This converts mentions to comments if the content is short enough.
=> Short Mentions

includes/class-admin.php, includes/class-cli.php, includes/functions.php
This allows the refreshing of webmentions from the Bulk Actions menu, assuming the original source is still available.
=> Allow refreshing webmentions from the Bulk Actions menu

includes/class-cli.php, includes/class-receiver.php
Resolves #360 as this will only set this property if it is a new comment.
=> Set created at time only for new comments.

includes/class-receiver.php
#399 This removes the filtering before adding the webmention, on the basis we do our own filtering in webmention_sanitize_html and restores it afterward.
=> Remove filter because we are already filtering

templates/webmention-comment-form.php, templates/webmention-endpoint-form.php
=> Client-side URl validation

includes/class-comment.php
=> link to source

assets/css/webmention.css, includes/class-discovery.php, templates/webmention-comments.php
This addresses #417. Tried to do this using a details and summary tag. Did some basic styling...think it could be better...but wanted to get some feedback.
=> Bring back overflow using a details tag

includes/Entity/class-item.php, includes/Handler/class-mf2.php
This adds a function to retrieve the author URL to get the name, photo, etc when it isn't embedded in the page and it fixes a PHP bug when something isn't a numeric array.
=> Repair Errors in the MF2 File

includes/class-discovery.php, includes/class-receiver.php, includes/functions.php
This moves the decision as to whether webmentions are open to a new webmentions_open function.
For this first phase, it still checks pings_open, so there is effectively no change. But this allows for changing this behavior in a future round.
=> Replace pings_open with new wrapper function, webmentions_open 

languages/webmention.pot, readme.md, readme.txt, webmention.php
=> Bump version

includes/functions.php, readme.md, readme.txt, webmention.php
This is my fault...I don't know how I missed it, but need to fix it.
=> Mistake that should not have been missed

includes/class-comment.php, languages/webmention.pot, readme.md, readme.txt, webmention.php
See https://wordpress.org/support/topic/breaks-ordinary-comment-permalink-links/
=> fix comment_link issue

includes/Entity/class-item.php, includes/Handler/class-base.php, includes/Handler/class-meta.php, includes/Handler/class-mf2.php, includes/class-handler.php
if properties are not set and to avoid "anonymous".
fix #393
=> Improve fallback handling

includes/Handler/class-mf2.php
=> fix fatal error

includes/class-comment-walker.php, readme.md, readme.txt, webmention.php
Addresses https://wordpress.org/support/topic/plugin-strips-markup-from-non-webmention-comments
=> Comment style

includes/class-sender.php
See #465
Does that fix the issue @snarfed ?
=> Fix delete-webmentions

includes/Handler/class-mf2.php
=> Update class-mf2.php to flatten the haystack

.github/workflows/cp-phpunit.yml, .github/workflows/wp-phpunit.yml, bin/install-cp-tests.sh, composer.json, tests/bootstrap.php
This just runs the unit tests on the latest version of ClassicPress. At this time, multiple versions and PHP versions seems unnecessary.
=> Add single ClassicPress Unit Test

includes/class-autoloader.php, readme.md, webmention.php
Quick fix to respect the uppercase folder name.
=> Fix Autoloader
